services:
  px4:
    image: jonasvautherin/px4-gazebo-headless:1.16.1
    network_mode: host

  # mavp2p:
  #   image: bluenviron/mavp2p
  #   network_mode: host
  #   command:
  #     - udps:0.0.0.0:14540
  #     - udpc:0.0.0.0:5600
  #     - udpc:0.0.0.0:5700
